export const DEFAULT_PIPELINE_MAX_ATTEMPTS = 3;
export const DEFAULT_BACKOFF_BASE_SECONDS = 30;
export const DEFAULT_BACKOFF_MAX_SECONDS = 900;

export const PIPELINE_STAGE_ORDER = [
  'DISCOVERED',
  'DOWNLOADING',
  'VALIDATING',
  'HASHING',
  'UPLOADING_TO_S3',
  'STORED_IN_S3',
  'GENERATING_METADATA',
  'METADATA_GENERATED',
  'GENERATING_EMBEDDING',
  'EMBEDDING_GENERATED',
  'COMPLETED',
] as const;
