import { ComponentType } from '../constants/flashcard.constants';

export interface TemplateComponentDefinition {
  componentId: string;
  componentType: ComponentType;
  editable: boolean;
  required: boolean;
  validationRules?: Record<string, unknown>;
  regionId?: string;
}

export interface TemplateLayoutComponent {
  id: string;
  type: string;
  editable?: boolean;
  required?: boolean;
  validationRules?: Record<string, unknown>;
}

export interface TemplateLayoutRegion {
  id: string;
  components: TemplateLayoutComponent[];
}

/** Region-based layout. Editable flags live on each component. */
export interface TemplateLayoutDefinition {
  regions: TemplateLayoutRegion[];
}

export interface TemplateSelectionCriteria {
  ageMin?: number | null;
  ageMax?: number | null;
  ageGroup?: string;
  age?: number;
  grade?: string;
  subject?: string;
  topic?: string;
  learningObjective?: string;
  intent?: string;
  difficulty?: string;
}

export interface ScoredTemplateMatch {
  templateId: string;
  ruleId: string;
  ruleName: string;
  priority: number;
  score: number;
}

/** Structured image search query generated by the LLM (never filenames). */
export interface ImageSearchQuery {
  searchQuery: string;
  expectedObjects: string[];
  preferredStyle?: string;
  preferredBackground?: string;
  orientation?: string;
  educationalUse?: string;
}

export interface LlmCardContent {
  cardIndex: number;
  /** Text content keyed by the selected template's text componentId. */
  textComponents: Record<string, string>;
  /** Image search instructions keyed by the selected template's image componentId. */
  imageComponents: Record<string, ImageSearchQuery>;
}

export interface LlmFlashcardPayload {
  cards: LlmCardContent[];
  resolvedLearningObjective?: string;
}

export type ImageRetrievalStatus =
  | 'found'
  | 'not_found'
  | 'IMAGE_NOT_FOUND'
  | 'timeout'
  | 'error';

export interface AssetReference {
  assetId: string | null;
  s3ObjectKey: string | null;
  signedUrl: string | null;
  /** Same-origin proxy path; avoids S3 CORS for canvas-based renderers. */
  imageUrl: string | null;
  caption: string | null;
  similarity: number | null;
  mimeType: string | null;
  status: ImageRetrievalStatus;
  queryUsed: string;
  attempts: string[];
}

export interface EditableComponentPayload {
  componentId: string;
  /** Alias of componentType for FLASH_CARD_REVISED response contract. */
  type: ComponentType;
  componentType: ComponentType;
  editable: boolean;
  content: string | null;
  validationRules?: Record<string, unknown>;
  assetReference?: AssetReference | null;
}

export interface FlashcardCardPayload {
  cardId: string;
  cardIndex: number;
  components: EditableComponentPayload[];
}

export interface SelectedTemplatePayload {
  id: string;
  name: string;
  description: string | null;
  templateType: string;
  layoutType: string;
  templateVersion: string;
  supportedAgeGroups: string[];
  supportedGrades: string[];
  learningObjectives: string[];
  subjectsSupported: string[];
  difficultyLevels: string[];
  tags: string[];
  pageSize: string;
  orientation: string;
  thumbnail: string | null;
  layoutDefinition: TemplateLayoutDefinition | unknown;
  active?: boolean;
}

export interface GenerateFlashcardsResponse {
  request: {
    query: string;
    topic: string;
    ageGroup: string;
    ageMin: number;
    ageMax: number;
    grade: string | null;
    subject: string | null;
    difficulty: string;
    language: string;
    learningObjective: string;
    educationalIntent: string;
    count: number;
  };
  selection: {
    ruleId: string;
    ruleName: string;
    score: number;
    priority: number;
  };
  template: SelectedTemplatePayload;
  templateVersion: string;
  layoutDefinition: TemplateLayoutDefinition | unknown;
  cards: FlashcardCardPayload[];
  metadata: {
    generatedAt: string;
    promptVersion: string;
    contentModel: string;
    imageConcurrency: number;
    requestId?: string;
    executionId?: string;
    correlationId?: string;
  };
  /** @deprecated Prefer metadata — kept for flashcards.html compatibility */
  renderingMetadata: {
    generatedAt: string;
    promptVersion: string;
    contentModel: string;
    imageConcurrency: number;
    requestId?: string;
    executionId?: string;
    correlationId?: string;
  };
}

export type FlashcardErrorCode =
  | 'INVALID_REQUEST'
  | 'NO_TEMPLATE_FOUND'
  | 'UNSUPPORTED_AGE'
  | 'UNSUPPORTED_SUBJECT'
  | 'UNKNOWN_LEARNING_OBJECTIVE'
  | 'INVALID_LLM_OUTPUT'
  | 'LLM_TIMEOUT'
  | 'RETRY_EXHAUSTION'
  | 'TEMPLATE_VERSION_MISMATCH'
  | 'MISSING_EDITABLE_COMPONENT'
  | 'IMAGE_SEARCH_TIMEOUT'
  | 'PARTIAL_IMAGE_FAILURE';
