-- Seed banned content-restriction terms (idempotent).
-- prisma migrate only creates schema; this data migration inserts the lists.

INSERT INTO "ContentRestrictionTerm" (
  "id",
  "term",
  "category",
  "severity",
  "countryCode",
  "active",
  "notes",
  "createdAt",
  "updatedAt"
)
SELECT
  md5(concat_ws(':', v.term, v."countryCode", v.severity)),
  v.term,
  v.category::"ContentRestrictionCategory",
  v.severity::"ContentRestrictionSeverity",
  v."countryCode",
  true,
  v.notes,
  CURRENT_TIMESTAMP,
  CURRENT_TIMESTAMP
FROM (
  VALUES
    -- Global bans
    ('god', 'RELIGIOUS', 'BANNED', '*', 'Global forbidden terms'),
    ('gods', 'RELIGIOUS', 'BANNED', '*', 'Global forbidden terms'),
    ('jesus', 'RELIGIOUS', 'BANNED', '*', 'Global forbidden terms'),
    ('christ', 'RELIGIOUS', 'BANNED', '*', 'Global forbidden terms'),
    ('allah', 'RELIGIOUS', 'BANNED', '*', 'Global forbidden terms'),
    ('muslim', 'RELIGIOUS', 'BANNED', '*', 'Global forbidden terms'),
    ('islam', 'RELIGIOUS', 'BANNED', '*', 'Global forbidden terms'),
    ('quran', 'RELIGIOUS', 'BANNED', '*', 'Global forbidden terms'),
    ('buddha', 'RELIGIOUS', 'BANNED', '*', 'Global forbidden terms'),
    ('sikh', 'RELIGIOUS', 'BANNED', '*', 'Global forbidden terms'),
    ('jewish', 'RELIGIOUS', 'BANNED', '*', 'Global forbidden terms'),
    ('judaism', 'RELIGIOUS', 'BANNED', '*', 'Global forbidden terms'),
    ('torah', 'RELIGIOUS', 'BANNED', '*', 'Global forbidden terms'),
    ('prayer', 'RELIGIOUS', 'BANNED', '*', 'Global forbidden terms'),
    ('worship', 'RELIGIOUS', 'BANNED', '*', 'Global forbidden terms'),
    ('angel', 'RELIGIOUS', 'BANNED', '*', 'Global forbidden terms'),
    ('saint', 'RELIGIOUS', 'BANNED', '*', 'Global forbidden terms'),
    ('holy', 'RELIGIOUS', 'BANNED', '*', 'Global forbidden terms'),
    ('sacred', 'RELIGIOUS', 'BANNED', '*', 'Global forbidden terms'),
    ('bible', 'RELIGIOUS', 'BANNED', '*', 'Global forbidden terms'),
    ('scripture', 'RELIGIOUS', 'BANNED', '*', 'Global forbidden terms'),
    ('religion', 'RELIGIOUS', 'BANNED', '*', 'Global forbidden terms'),
    ('religious', 'RELIGIOUS', 'BANNED', '*', 'Global forbidden terms'),
    ('devil', 'RELIGIOUS', 'BANNED', '*', 'Global forbidden terms'),
    ('satan', 'RELIGIOUS', 'BANNED', '*', 'Global forbidden terms'),
    ('demon', 'RELIGIOUS', 'BANNED', '*', 'Global forbidden terms'),
    ('deity', 'RELIGIOUS', 'BANNED', '*', 'Global forbidden terms'),
    ('pastor', 'RELIGIOUS', 'BANNED', '*', 'Global forbidden terms'),
    ('nun', 'RELIGIOUS', 'BANNED', '*', 'Global forbidden terms'),
    ('monk', 'RELIGIOUS', 'BANNED', '*', 'Global forbidden terms'),
    ('heaven', 'RELIGIOUS', 'BANNED', '*', 'Global forbidden terms'),
    ('hell', 'RELIGIOUS', 'BANNED', '*', 'Global forbidden terms'),
    ('easter', 'RELIGIOUS', 'BANNED', '*', 'Global forbidden terms'),
    ('diwali', 'RELIGIOUS', 'BANNED', '*', 'Global forbidden terms'),
    ('hanukkah', 'RELIGIOUS', 'BANNED', '*', 'Global forbidden terms'),
    ('passover', 'RELIGIOUS', 'BANNED', '*', 'Global forbidden terms'),
    ('eid', 'RELIGIOUS', 'BANNED', '*', 'Global forbidden terms'),
    ('holi', 'RELIGIOUS', 'BANNED', '*', 'Global forbidden terms'),
    ('ramadan', 'RELIGIOUS', 'BANNED', '*', 'Global forbidden terms'),
    ('sin', 'RELIGIOUS', 'BANNED', '*', 'Global forbidden terms'),
    ('miracle', 'RELIGIOUS', 'BANNED', '*', 'Global forbidden terms'),
    ('prophet', 'RELIGIOUS', 'BANNED', '*', 'Global forbidden terms'),
    ('apostle', 'RELIGIOUS', 'BANNED', '*', 'Global forbidden terms'),
    ('disciple', 'RELIGIOUS', 'BANNED', '*', 'Global forbidden terms'),
    ('resurrection', 'RELIGIOUS', 'BANNED', '*', 'Global forbidden terms'),
    ('creation', 'RELIGIOUS', 'BANNED', '*', 'Global forbidden terms'),
    ('faith', 'RELIGIOUS', 'BANNED', '*', 'Global forbidden terms'),
    ('praise', 'RELIGIOUS', 'BANNED', '*', 'Global forbidden terms'),
    ('bless', 'RELIGIOUS', 'BANNED', '*', 'Global forbidden terms'),
    ('blessed', 'RELIGIOUS', 'BANNED', '*', 'Global forbidden terms'),
    ('blessing', 'RELIGIOUS', 'BANNED', '*', 'Global forbidden terms'),
    ('redeem', 'RELIGIOUS', 'BANNED', '*', 'Global forbidden terms'),
    ('redemption', 'RELIGIOUS', 'BANNED', '*', 'Global forbidden terms'),
    ('salvation', 'RELIGIOUS', 'BANNED', '*', 'Global forbidden terms'),
    ('almighty', 'RELIGIOUS', 'BANNED', '*', 'Global forbidden terms'),
    ('eternal', 'RELIGIOUS', 'BANNED', '*', 'Global forbidden terms'),
    ('heavenly', 'RELIGIOUS', 'BANNED', '*', 'Global forbidden terms'),
    ('divine', 'RELIGIOUS', 'BANNED', '*', 'Global forbidden terms'),
    ('commandment', 'RELIGIOUS', 'BANNED', '*', 'Global forbidden terms'),
    ('covenant', 'RELIGIOUS', 'BANNED', '*', 'Global forbidden terms'),
    ('gospel', 'RELIGIOUS', 'BANNED', '*', 'Global forbidden terms'),
    ('revelation', 'RELIGIOUS', 'BANNED', '*', 'Global forbidden terms'),
    ('prophecy', 'RELIGIOUS', 'BANNED', '*', 'Global forbidden terms'),
    -- SA
    ('pig', 'ANIMAL_FOOD', 'BANNED', 'SA', 'Saudi Arabia'),
    ('pigs', 'ANIMAL_FOOD', 'BANNED', 'SA', 'Saudi Arabia'),
    ('piglet', 'ANIMAL_FOOD', 'BANNED', 'SA', 'Saudi Arabia'),
    ('hog', 'ANIMAL_FOOD', 'BANNED', 'SA', 'Saudi Arabia'),
    ('swine', 'ANIMAL_FOOD', 'BANNED', 'SA', 'Saudi Arabia'),
    ('ham', 'ANIMAL_FOOD', 'BANNED', 'SA', 'Saudi Arabia'),
    ('bacon', 'ANIMAL_FOOD', 'BANNED', 'SA', 'Saudi Arabia'),
    ('pork', 'ANIMAL_FOOD', 'BANNED', 'SA', 'Saudi Arabia'),
    ('pepperoni', 'ANIMAL_FOOD', 'BANNED', 'SA', 'Saudi Arabia'),
    ('prosciutto', 'ANIMAL_FOOD', 'BANNED', 'SA', 'Saudi Arabia'),
    ('lard', 'ANIMAL_FOOD', 'BANNED', 'SA', 'Saudi Arabia'),
    -- IN
    ('cow', 'ANIMAL_FOOD', 'BANNED', 'IN', 'India'),
    ('cows', 'ANIMAL_FOOD', 'BANNED', 'IN', 'India'),
    ('calf', 'ANIMAL_FOOD', 'BANNED', 'IN', 'India'),
    ('beef', 'ANIMAL_FOOD', 'BANNED', 'IN', 'India'),
    ('veal', 'ANIMAL_FOOD', 'BANNED', 'IN', 'India'),
    ('bull', 'ANIMAL_FOOD', 'BANNED', 'IN', 'India'),
    ('ox', 'ANIMAL_FOOD', 'BANNED', 'IN', 'India'),
    -- IL
    ('pig', 'ANIMAL_FOOD', 'BANNED', 'IL', 'Israel'),
    ('pork', 'ANIMAL_FOOD', 'BANNED', 'IL', 'Israel'),
    ('ham', 'ANIMAL_FOOD', 'BANNED', 'IL', 'Israel'),
    ('bacon', 'ANIMAL_FOOD', 'BANNED', 'IL', 'Israel'),
    ('shellfish', 'ANIMAL_FOOD', 'BANNED', 'IL', 'Israel'),
    ('shrimp', 'ANIMAL_FOOD', 'BANNED', 'IL', 'Israel'),
    ('lobster', 'ANIMAL_FOOD', 'BANNED', 'IL', 'Israel'),
    ('crab', 'ANIMAL_FOOD', 'BANNED', 'IL', 'Israel'),
    -- TR
    ('pig', 'ANIMAL_FOOD', 'BANNED', 'TR', 'Turkey'),
    ('pork', 'ANIMAL_FOOD', 'BANNED', 'TR', 'Turkey'),
    ('ham', 'ANIMAL_FOOD', 'BANNED', 'TR', 'Turkey'),
    ('bacon', 'ANIMAL_FOOD', 'BANNED', 'TR', 'Turkey')
) AS v(term, category, severity, "countryCode", notes)
ON CONFLICT ("term", "countryCode", "severity") DO NOTHING;
