import { PIPELINE_STAGES } from '../../../common/events/pipeline-tracker.events';
import { WORKSHEET_GENERATE_STAGES } from './worksheet-pipeline.events';

describe('worksheet pipeline stages', () => {
  it('includes every generate-pipeline step in order', () => {
    expect([...WORKSHEET_GENERATE_STAGES]).toEqual([
      PIPELINE_STAGES.REQUEST_VALIDATION,
      PIPELINE_STAGES.REQUEST_ANALYSIS,
      PIPELINE_STAGES.TEMPLATE_SELECTION,
      PIPELINE_STAGES.LLM_CONTENT_GENERATION,
      PIPELINE_STAGES.PROMPT_GENERATION,
      PIPELINE_STAGES.LLM_REQUEST,
      PIPELINE_STAGES.CONTENT_VALIDATION,
      PIPELINE_STAGES.IMAGE_QUERY_GENERATION,
      PIPELINE_STAGES.IMAGE_RETRIEVAL,
      PIPELINE_STAGES.IMAGE_MAPPING,
      PIPELINE_STAGES.STRUCTURE_VALIDATION,
      PIPELINE_STAGES.PERSISTENCE,
      PIPELINE_STAGES.RESPONSE_ASSEMBLY,
      PIPELINE_STAGES.FINAL_VALIDATION,
      PIPELINE_STAGES.RESPONSE_RETURN,
    ]);
  });
});
