export enum AssetState {
  DISCOVERED = 'DISCOVERED',
  DOWNLOADING = 'DOWNLOADING',
  VALIDATING = 'VALIDATING',
  HASHING = 'HASHING',
  DUPLICATE_CHECK = 'DUPLICATE_CHECK',
  UPLOADING_TO_S3 = 'UPLOADING_TO_S3',
  STORED_IN_S3 = 'STORED_IN_S3',
  GENERATING_METADATA = 'GENERATING_METADATA',
  METADATA_GENERATED = 'METADATA_GENERATED',
  GENERATING_EMBEDDING = 'GENERATING_EMBEDDING',
  EMBEDDING_GENERATED = 'EMBEDDING_GENERATED',
  COMPLETED = 'COMPLETED',
  FAILED = 'FAILED',
  RETRY_PENDING = 'RETRY_PENDING',
  DEAD_LETTER = 'DEAD_LETTER',
}

export enum JobState {
  CREATED = 'CREATED',
  SCANNING = 'SCANNING',
  PROCESSING = 'PROCESSING',
  COMPLETED = 'COMPLETED',
  COMPLETED_WITH_ERRORS = 'COMPLETED_WITH_ERRORS',
  FAILED = 'FAILED',
  CANCELLED = 'CANCELLED',
}

export enum SourceType {
  GOOGLE_DRIVE = 'GOOGLE_DRIVE',
  S3_BUCKET = 'S3_BUCKET',
  LOCAL_STORAGE = 'LOCAL_STORAGE',
}
